# Generated by Django 5.0.6 on 2024-06-02 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='validity_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
